/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Variant({
  'mason' : IDL.Null,
  'plumber' : IDL.Null,
  'labour' : IDL.Null,
  'electrician' : IDL.Null,
  'jcbOperator' : IDL.Null,
  'painter' : IDL.Null,
  'driver' : IDL.Null,
  'carpenter' : IDL.Null,
});
export const JobPosting = IDL.Record({
  'id' : IDL.Principal,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
  'location' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const WorkerProfile = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'experienceYears' : IDL.Nat,
  'category' : Category,
  'phone' : IDL.Text,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getJobPosting' : IDL.Func([IDL.Principal], [IDL.Opt(JobPosting)], ['query']),
  'getJobsByCategory' : IDL.Func([Category], [IDL.Vec(JobPosting)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkerProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(WorkerProfile)],
      ['query'],
    ),
  'getWorkersByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(WorkerProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'postJob' : IDL.Func(
      [IDL.Text, Category, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'registerWorkerProfile' : IDL.Func(
      [IDL.Text, IDL.Text, Category, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Variant({
    'mason' : IDL.Null,
    'plumber' : IDL.Null,
    'labour' : IDL.Null,
    'electrician' : IDL.Null,
    'jcbOperator' : IDL.Null,
    'painter' : IDL.Null,
    'driver' : IDL.Null,
    'carpenter' : IDL.Null,
  });
  const JobPosting = IDL.Record({
    'id' : IDL.Principal,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
    'location' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'phone' : IDL.Text });
  const WorkerProfile = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'experienceYears' : IDL.Nat,
    'category' : Category,
    'phone' : IDL.Text,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getJobPosting' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(JobPosting)],
        ['query'],
      ),
    'getJobsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(JobPosting)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkerProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(WorkerProfile)],
        ['query'],
      ),
    'getWorkersByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(WorkerProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'postJob' : IDL.Func(
        [IDL.Text, Category, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'registerWorkerProfile' : IDL.Func(
        [IDL.Text, IDL.Text, Category, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };