/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'mason' : null } |
  { 'plumber' : null } |
  { 'labour' : null } |
  { 'electrician' : null } |
  { 'jcbOperator' : null } |
  { 'painter' : null } |
  { 'driver' : null } |
  { 'carpenter' : null };
export interface JobPosting {
  'id' : Principal,
  'title' : string,
  'description' : string,
  'category' : Category,
  'location' : string,
  'contactPhone' : string,
}
export interface UserProfile { 'name' : string, 'phone' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkerProfile {
  'id' : Principal,
  'name' : string,
  'description' : string,
  'experienceYears' : bigint,
  'category' : Category,
  'phone' : string,
  'location' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllJobPostings' : ActorMethod<[], Array<JobPosting>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getJobPosting' : ActorMethod<[Principal], [] | [JobPosting]>,
  'getJobsByCategory' : ActorMethod<[Category], Array<JobPosting>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkerProfile' : ActorMethod<[Principal], [] | [WorkerProfile]>,
  'getWorkersByCategory' : ActorMethod<[Category], Array<WorkerProfile>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'postJob' : ActorMethod<
    [string, Category, string, string, string],
    undefined
  >,
  'registerWorkerProfile' : ActorMethod<
    [string, string, Category, string, bigint, string],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];